apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
    source: freshcloud
  name: ${APP_NAME}
  namespace: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - image: ${IMAGE}
          name: ${APP_NAME}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: '8888'
            - name: APP
              value: applications/basic-server/build/libs/basic-server-1.0-SNAPSHOT.jar
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
  namespace: ${APP_NAME}
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: ${APP_NAME}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP_NAME}
  namespace: ${APP_NAME}
  labels:
    app: ${APP_NAME}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: contour
    ingress.kubernetes.io/force-ssl-redirect: "true"
    projectcontour.io/websocket-routes: "/"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: ${APP_NAME}.${DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: ${APP_NAME}
                port:
                  number: 8888
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - ${APP_NAME}.${DOMAIN}
      secretName: ${APP_NAME}-cert
