apiVersion: v1
kind: ServiceAccount
metadata:
  name: kotlin-ktor-starter-service-account
  namespace: kotlin-ktor-starter
secrets:
  - name: kotlin-ktor-starter-registry-credentials
imagePullSecrets:
  - name: kotlin-ktor-starter-registry-credentials
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: kotlin-ktor-starter-builder
  namespace: kotlin-ktor-starter
spec:
  serviceAccount: kotlin-ktor-starter-service-account
  tag: registry.$REGISTRY_DOMAIN/kpack/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: heroku/java
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: kotlin-ktor-starter-image
  namespace: kotlin-ktor-starter
spec:
  tag: registry.$REGISTRY_DOMAIN/kpack/kotlin-ktor-starter
  serviceAccount: kotlin-ktor-starter-service-account
  builder:
    name: kotlin-ktor-starter-builder
    kind: Builder
  source:
    git:
      url: https://github.com/initialcapacity/kotlin-ktor-starter
      revision: main
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kotlin-ktor-starter
  name: kotlin-ktor-starter-image-role
rules:
  - apiGroups: [ "kpack.io", "", "networking.k8s.io", "apps" ]
    resources: [ "images", "builds", "pods", "pods/log", "services", "ingresses", "deployments" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kotlin-ktor-starter-image-role-binding
  namespace: kotlin-ktor-starter
subjects:
  - kind: ServiceAccount
    name: kotlin-ktor-starter-service-account
    apiGroup: ""
roleRef:
  kind: Role
  name: kotlin-ktor-starter-image-role
  apiGroup: ""