apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-collector
    source: freshcloud
  name: data-collector
  namespace: kotlin-ktor-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
        - image: ${IMAGE}
          name: data-collector
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: '8886'
            - name: APP
              value: applications/data-collector-server/build/libs/data-collector-server-1.0-SNAPSHOT.jar
          ports:
            - containerPort: 8886
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-collector
  name: data-collector
  namespace: kotlin-ktor-starter
spec:
  ports:
    - port: 8886
      protocol: TCP
      targetPort: 8886
  selector:
    app: data-collector
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-analyzer
    source: freshcloud
  name: data-analyzer
  namespace: kotlin-ktor-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-analyzer
  template:
    metadata:
      labels:
        app: data-analyzer
    spec:
      containers:
        - image: ${IMAGE}
          name: data-analyzer
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: '8887'
            - name: APP
              value: applications/data-analyzer-server/build/libs/data-analyzer-server-1.0-SNAPSHOT.jar
          ports:
            - containerPort: 8887
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-analyzer
  name: data-analyzer
  namespace: kotlin-ktor-starter
spec:
  ports:
    - port: 8887
      protocol: TCP
      targetPort: 8887
  selector:
    app: data-analyzer
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kotlin-ktor-starter
    source: freshcloud
  name: kotlin-ktor-starter
  namespace: kotlin-ktor-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotlin-ktor-starter
  template:
    metadata:
      labels:
        app: kotlin-ktor-starter
    spec:
      containers:
        - image: ${IMAGE}
          name: kotlin-ktor-starter
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PORT
              value: '8888'
            - name: APP
              value: applications/basic-server/build/libs/basic-server-1.0-SNAPSHOT.jar
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kotlin-ktor-starter
  name: kotlin-ktor-starter
  namespace: kotlin-ktor-starter
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: kotlin-ktor-starter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kotlin-ktor-starter
  namespace: kotlin-ktor-starter
  labels:
    app: kotlin-ktor-starter
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: contour
    ingress.kubernetes.io/force-ssl-redirect: "true"
    projectcontour.io/websocket-routes: "/"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: kotlin-ktor-starter.${DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: kotlin-ktor-starter
                port:
                  number: 8888
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - kotlin-ktor-starter.${DOMAIN}
      secretName: kotlin-ktor-starter-cert
