apiVersion: v1
kind: Service
metadata:
  name: basic-server
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "config-default"}'
  labels:
    app: basic-server
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: basic-server
    tier: frontend